version: '3.8'

services:
  db:
    container_name: ${PSQL_HOST}
    image: postgres:15.1
    environment:
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    volumes:
      - pgsql_data:/var/lib/postgresql/data/

  backend:
    container_name: svit_it_backend
    build: ./
    volumes:
      - .:/app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  pgsql_data:
